version: '3.2'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - hello
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=daoyun

  adminer:
    image: adminer
    networks:
      - hello
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.hello.ltd`)"
      - "traefik.port=8080"

  whoami:
    image: traefik/whoami
    networks:
      - hello
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.hello.ltd`)"

networks:
  hello: 
    external: 
      name: hello

