version: '3.2'

services:
  hbase-master:
    image: bde2020/hbase-master:1.0.0-hbase1.2.6
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=hbase
        - traefik.http.routers.hbase-master.rule=Host(`hello.lidotcircle.ldy`)
        - traefik.port=16010
    env_file:
      - ./hbase.env

  hbase-regionserver-1:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-1

  hbase-regionserver-2:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-2

  hbase-regionserver-3:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-3

networks:
  hbase:
    external:
      name: hbase
